# vim: set ft=yaml ts=2 expandtab:
---

namespace: mafalb
name: openssh
version: 1.1.3
readme: README.md

authors:
- Markus Falb <markus.falb@mafalb.at>

description: Ansible collection openssh

license:
- GPL-3.0-or-later

tags:
- openssh
- ssh
- sshd

dependencies: {}

repository: https://github.com/mafalb/ansible-collection-openssh
documentation: https://github.com/mafalb/ansible-collection-openssh
homepage: https://github.com/mafalb/ansible-collection-openssh
issues: https://github.com/mafalb/ansible-collection-openssh/issues

...
