# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-openssh
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-openssh is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-openssh is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-openssh.
# If not, see <https://www.gnu.org/licenses/>.

---

sshd_default_config:
  HostKey:
  - /etc/ssh/ssh_host_rsa_key
  - /etc/ssh/ssh_host_ecdsa_key
  - /etc/ssh/ssh_host_ed25519_key
  SyslogFacility: "{{ sshd_syslogfacility }}"
  PermitRootLogin: without-password
  AuthorizedKeysFile: '.ssh/authorized_keys'
  PasswordAuthentication: 'yes'
  ChallengeResponseAuthentication: 'no'
  UsePAM: 'yes'
  X11Forwarding: 'yes'
  GSSAPIAuthentication: "{{ sshd_gssapiauth }}"
  PrintMotd: 'no'
  AcceptEnv:
  - LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
  - LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
  - LC_IDENTIFICATION LC_ALL LANGUAGE
  - XMODIFIERS
  Subsystem: sftp {{ sftp_subsystem }}

sshd:
  cfg: "{{ sshd_default_config|combine(sshd_config) }}"

sshd_validate: sshd -f %s -T -C user=gugu -C host=localhost -C addr=localhost

...
