# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
{% for var, value in item.env.items() %}
{% if value %}
ENV {{ var }} {{ value }}
{% endif %}
{% endfor %}
{% endif %}

RUN if [ $(command -v apt-get) ]; then apt-get update && apt-get install -y python3 python3-apt sudo systemd ;\
    elif [ $(command -v dnf) ]; then touch /var/lib/rpm/* && dnf makecache && dnf --assumeyes install python3 sudo which systemd iproute;\
    elif [ $(command -v microdnf) ]; then touch /var/lib/rpm/* && microdnf install python3 sudo which systemd iproute yum && touch /etc/yum/vars/ociregion;\
    elif [ $(command -v yum) ]; then yum makecache fast && yum install -y python sudo which yum-plugin-ovl iproute && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf; \
    elif [ $(command -v pacman) ]; then pacman -Sy && pacman --noconfirm -Sq core/python core/iproute2 core/sudo core/which core/systemd;\
    fi

RUN rm -f /run/nologin
