# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: prepare client
  hosts: client_group
  tasks:
    - name: openssh clients are present
      package:
        name: openssh-clients

- name: prepare server
  hosts: server_group
  tasks:
    - name: /run/nologin is absent
      file:
        path: /run/nologin
        state: absent
      when: false

...
