# vim: set ft=yaml ts=2 expandtab:
---

- name: converge clients
  hosts: proxy_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  tasks:

  # use the proxy as client for verify steps
  #
  - name: openssh clients are present
    package:
      name: openssh-clients

  - name: ssh user key is present
    openssh_keypair:
      path: /tmp/id_rsa_user
      type: rsa

  - name: ssh admin key is present
    openssh_keypair:
      path: /tmp/id_rsa_admin
      type: rsa


- name: converge servers
  hosts: all,!infrastructure_group

  environment:
    http_proxy: http://ci-proxy:3128
    https_proxy: http://ci-proxy:3128

  roles:

  - role: mafalb.openssh.sshd
    sshd_config_template: sshd_config.j2
    sftponly_group: sftpchroot

  tasks:

  - name: get public admin key
    delegate_to: ci-proxy
    command: cat /tmp/id_rsa_admin.pub
    changed_when: false
    register: _public_key_admin
    run_once: true

  - name: get public user key
    delegate_to: ci-proxy
    command: cat /tmp/id_rsa_user.pub
    changed_when: false
    register: _public_key_user
    run_once: true

  - name: user for ssh is present
    block:

    - name: user is present
      user:
        name: testssh1

    - name: authorized_keys is present
      authorized_key:
        user: testssh1
        key: "{{ _public_key_user.stdout }}"

  - name: user for chrooted sftp is present
    block:

    - name: group for chrooted sftp users is present
      group:
        name: sftpchroot

    - name: groups are present
      group:
        name: "{{ item }}"
      loop:
      - testsftp1
      - testsftp2

    - name: home directories are present
      file:
        path: /home/{{ item }}
        state: directory
        owner: root
        group: "{{ item }}"
        mode: 00750
      loop:
      - testsftp1
      - testsftp2


    - name: user is present
      user:
        name: "{{ item }}"
        create_home: false
        group: "{{ item }}"
        groups:
        - sftpchroot
      loop:
      - testsftp1
      - testsftp2

  - name: authorized_keys for admin is present
    include_role:
      name: mafalb.openssh.authorized_keys
    vars:
      group: sftpchroot
      keys: "{{ [ _public_key_admin.stdout ] }}"
      path: /etc/ssh/authorized_keys/sftpchroot
      manage_dir: false
      mode: '640'

  - name: authorized_keys for testsftp1 is present
    include_role:
      name: mafalb.openssh.authorized_keys
    vars:
      user: root
      group: testsftp1
      keys: "{{ [ _public_key_user.stdout ] }}"
      path: /home/testsftp1/.ssh/authorized_keys
      mode: '640'

  - name: testfile is present
    copy:
      content: testfile
      dest: /home/{{ item }}/1_testfile
      mode: 00644
    loop:
    - testsftp1
    - testsftp2

...
