# vim: set ft=yaml ts=2 expandtab:
---

- name: Converge
  hosts: proxy_group

  tasks:

  # use the proxy as client for verify steps
  #
  - name: openssh clients are present
    package:
      name: openssh-clients

  - name: ssh key is present
    openssh_keypair:
      path: /tmp/id_rsa
      type: rsa

- name: Converge
  hosts: all,!infrastructure_group
  roles:
  - role: mafalb.openssh.sshd

  tasks:

  - name: get public key
    delegate_to: ci_proxy
    command: cat /tmp/id_rsa.pub
    changed_when: false
    register: _public_key
    run_once: true

  - block:

    - name: user is present
      user:
        name: "{{ item }}"
      loop:
      - testssh1
      - testssh2

    - name: authorized_keys is present
      authorized_key:
        user: "{{ item }}"
        key: "{{ _public_key.stdout }}"
      loop:
      - testssh1
      - testssh2

...
