# vim: set ft=yaml ts=2 expandtab:
---

- debug: var=mode|type_debug
  tags:
  - never
  - debug

- name: assertions
  assert:
    that:
    - mode|type_debug == 'AnsibleUnicode'
    - path is defined
    - user is defined or group is defined

- name: .ssh directory is present
  file:
    path: "{{ path.split('/')[:-1]|join('/') }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group|default(user) }}"
    mode: "{{ directory_mode|default(mode|int(8) + 00110) }}"
    setype: ssh_home_t
  when: manage_dir is true

- name: authorized_keys is present
  template:
    src: authorized_keys.j2
    dest: "{{ path }}"
    owner: "{{ user|default(omit) }}"
    group: "{{ group|default(omit) }}"
    mode: "{{ mode|default(omit) }}"
    setype: ssh_home_t
    backup: true

...
