# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: debug mode
  debug: var=mode|type_debug
  tags:
  - never
  - debug

- name: assertions
  assert:
    that:
    - mode|type_debug == 'AnsibleUnicode'
    - path is defined
    - user is defined or group is defined

- name: .ssh directory is present
  file:
    path: "{{ path.split('/')[:-1]|join('/') }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group|default(user) }}"
    mode: "{{ (directory_mode|default(mode|int(8) + '110'|int(8)))|str }}"
    setype: ssh_home_t
  when: manage_dir|bool

- name: authorized_keys is present
  template:
    src: authorized_keys.j2
    dest: "{{ path }}"
    owner: "{{ user|default(omit) }}"
    group: "{{ group|default(omit) }}"
    mode: "{{ mode|default(omit) }}"
    setype: ssh_home_t
    backup: true

...
