# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-openssh
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-openssh is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-openssh is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-openssh.
# If not, see <https://www.gnu.org/licenses/>.

---

- debug: var=mode|type_debug
  tags:
  - never
  - debug

- name: assertions
  assert:
    that:
    - mode|type_debug == 'AnsibleUnicode'
    - path is defined
    - user is defined or group is defined

- name: .ssh directory is present
  file:
    path: "{{ path.split('/')[:-1]|join('/') }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group|default(user) }}"
    mode: "{{ directory_mode|default(mode|int(8) + 00110) }}"
    setype: ssh_home_t
  when: manage_dir|bool

- name: authorized_keys is present
  template:
    src: authorized_keys.j2
    dest: "{{ path }}"
    owner: "{{ user|default(omit) }}"
    group: "{{ group|default(omit) }}"
    mode: "{{ mode|default(omit) }}"
    setype: ssh_home_t
    backup: true

...
