# vim: set ft=yaml ts=2 expandtab:

# This file is part of ansible-collection-openssh
# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
#
# ansible-collection-openssh is free software: you can redistribute it 
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# ansible-collection-openssh is distributed in the hope that it will be
# useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with ansible-collection-openssh.
# If not, see <https://www.gnu.org/licenses/>.

---

- name: get OS specific variables
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}.yml"
  include_vars:
    file: "{{ item }}"

- name: assertions
  assert:
    that:
    - sshd_packages is defined
    - sshd_service is defined
    - sshd_state in [ 'present', 'absent' ]
    - sshd_config|type_debug == 'dict'
    - sshd.cfg|type_debug == 'dict'

- name: include_tasks for {{ sshd_state }}
  include_tasks: "{{ sshd_state }}.yml"

...
