# vim: set ft=yaml ts=2 expandtab:
---

- name: get OS specific variables
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}.yml"
  include_vars:
    file: "{{ item }}"

- name: assertions
  assert:
    that:
    - sshd_packages is defined
    - sshd_service is defined
    - sshd_state in [ 'present', 'absent' ]

- name: include_tasks for {{ sshd_state }}
  include_tasks: "{{ sshd_state }}.yml"

...
