# Copyright (c) 2021 Markus Falb <markus.falb@mafalb.at>
# GNU General Public License v3.0+
# see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt
---

- name: reset mafalb_error
  set_fact:
    mafalb_error: None

- name: get OS specific variables
  with_first_found:
  - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  - "{{ ansible_os_family }}.yml"
  include_vars:
    file: "{{ item }}"


- name: assertions
  assert:
    that:
    - sshd_packages is defined
    - sshd_service is defined
    - sshd_state in [ 'present', 'absent' ]
    - sshd_config|type_debug == 'dict'
    - sshd.cfg|type_debug == 'dict'

- block:
  - name: check that mode is given as string
    assert:
      that:
      - sshd_config_mode|default("")|type_debug in ['str', 'AnsibleUnicode']
      success_msg: "{{ sshd_config_mode|default('') }} is a string"
      fail_msg: "{{ sshd_config_mode|default('') }} is not a string"
  rescue:
  - name: set a fact
    set_fact:
      mafalb_error: mode not a string
  - name: fail
    fail:
      msg: "mode not a string: {{ sshd_config_mode|default('') }}"


- name: include_tasks for {{ sshd_state }}
  include_tasks: "{{ sshd_state }}.yml"

...
