# vim: set ft=yaml ts=2 expandtab:
---

name: UNSTABLE

on: 

  push:
    branches:
    - '**'
    tags-ignore:
    - '*'

  schedule:
  - cron: '40 12 * * 6'

  workflow_dispatch:

jobs:

  UNSTABLE:

    runs-on: ubuntu-20.04

    strategy:

      fail-fast: false

      matrix:

        target:
        - arch
        - fedora35
        - c9s
        - ubuntu2110

        ansible_version:
        - '2.9'
        - '2.10'
        - '2.11'

        include:

        - target: arch
          image: docker.io/archlinux:latest

        - target: fedora35
          image: quay.io/fedora/fedora:35-x86_64

        - target: c9s
          image: quay.io/centos/centos:stream9-development

        - target: ubuntu2110
          image: docker.io/ubuntu:impish

    env:
      
      ANSIBLE_VERSION: ${{ matrix.ansible_version }}
      CI_IMAGE: ${{ matrix.image }}
      CI_HOSTNAME: ci-${{ matrix.target }}
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      
    defaults:
      run:
        working-directory: ansible_collections/mafalb/openssh

    steps:

    - name: checkout collection mafalb.openssh
      uses: actions/checkout@v2
      with:
        path: ansible_collections/mafalb/openssh

    # use the github actions ansible
    #
    - name: get mafalb.ansible
      run: ansible-galaxy collection install mafalb.ansible

    # use the system ansible
    #
    - name: install molecule
      run: |
        sudo apt-get install ansible
        /usr/bin/ansible-playbook -D ~/.ansible/collections/ansible_collections/mafalb/ansible/playbooks/molecule.yml -e molecule_ansible_version=${{ matrix.ansible_version }} -t all,debug

    # use our ansible
    #
    - name: check ansible version
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        ansible --version | grep "^ansible.* ${{ matrix.ansible_version }}"

    - name: molecule tests
      run: |
        source ~/.virtualenvs/molecule/bin/activate
        molecule test
